// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Tft3.5MeIno

#ifndef _TFT3_5MEINO_UI_H
#define _TFT3_5MEINO_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "..\lvgl\lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Opn.h"
#include "screens/ui_Dark.h"
#include "screens/ui_Light.h"
#include "screens/ui_Clk.h"
#include "screens/ui_PlsSet.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

void ui_event____initial_actions0(lv_event_t * e);
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_imgopape_png);    // assets/imgOpAPE.png
LV_IMG_DECLARE(ui_img_imgophnd_png);    // assets/imgOpHND.png
LV_IMG_DECLARE(ui_img_imgopkws_png);    // assets/imgOpKWS.png
LV_IMG_DECLARE(ui_img_imgopszk_png);    // assets/imgOpSZK.png
LV_IMG_DECLARE(ui_img_imgopymh_png);    // assets/imgOpYMH.png
LV_IMG_DECLARE(ui_img_imgbg_dark_png);    // assets/imgBG_Dark.png
LV_IMG_DECLARE(ui_img_imglfw_png);    // assets/imgLFW.png
LV_IMG_DECLARE(ui_img_imgdaylight_png);    // assets/imgDayLight.png
LV_IMG_DECLARE(ui_img_imgneut_png);    // assets/imgNeut.png
LV_IMG_DECLARE(ui_img_imgtagauge_png);    // assets/imgTaGauge.png
LV_IMG_DECLARE(ui_img_imgbg_light_png);    // assets/imgBG_Light.png

// FONTS
LV_FONT_DECLARE(ui_font_Font30);
LV_FONT_DECLARE(ui_font_N200);
LV_FONT_DECLARE(ui_font_NUM120);
LV_FONT_DECLARE(ui_font_Num60);
LV_FONT_DECLARE(ui_font_Sp100);
LV_FONT_DECLARE(ui_font_Sp200);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
