// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Tft3.5MeIno

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void initEvent(lv_event_t * e);
void OpnTouch(lv_event_t * e);
void TripClickD(lv_event_t * e);
void TripLongD(lv_event_t * e);
void LfwLongD(lv_event_t * e);
void TripClickL(lv_event_t * e);
void TripLongL(lv_event_t * e);
void LfwLongL(lv_event_t * e);
void PlsSetRst(lv_event_t * e);
void PlsSetCalibSp(lv_event_t * e);
void PlsSetCalibOdo(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
