// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Tft3.5MeIno
#include <Arduino.h>
#include "ui.h"
#include "../myApplMain.h"
#include "../myOdoTrip.h"
#include "../myDispCtrl.h"

static lv_timer_t * appl_timer;

/* --------------------------------------------------------------- System Event */
void initEvent(lv_event_t * e)
{

}

/* ---------------------------------------------------------------- user Events */
void OpnTouch(lv_event_t * e)
{
	myDispCtrl_SwOpnImg();
}

void TripClickD(lv_event_t * e)
{
	myDispCtrl_SwOdoTrip();
}

void TripLongD(lv_event_t * e)
{
	myOdoTrip_TripReset();
}

void LfwLongD(lv_event_t * e)
{
	myOdoTrip_TripReset();
}

void TripClickL(lv_event_t * e)
{
	myDispCtrl_SwOdoTrip();
}

void TripLongL(lv_event_t * e)
{
	myOdoTrip_TripReset();
}

void LfwLongL(lv_event_t * e)
{
	myOdoTrip_TripReset();
}

void PlsSetRst(lv_event_t * e)
{
	myOdoTrip_CalibPlsReset();
}

void PlsSetCalibSp(lv_event_t * e)
{
	myOdoTrip_CalibSpPlsRate();
}

void PlsSetCalibOdo(lv_event_t * e)
{
	myOdoTrip_CalibSpPlsRate();
}
