// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Tft3.5MeIno

#include "../ui.h"

// COMPONENT TachoBar

lv_obj_t * ui_TachoBar_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_TachoBar;
    cui_TachoBar = lv_arc_create(comp_parent);
    lv_obj_set_width(cui_TachoBar, 300);
    lv_obj_set_height(cui_TachoBar, 300);
    lv_obj_set_x(cui_TachoBar, -20);
    lv_obj_set_y(cui_TachoBar, 0);
    lv_obj_set_align(cui_TachoBar, LV_ALIGN_CENTER);
    lv_obj_remove_flag(cui_TachoBar, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_arc_set_range(cui_TachoBar, 0, 48);
    lv_arc_set_value(cui_TachoBar, 48);
    lv_arc_set_bg_angles(cui_TachoBar, 135, 315);
    lv_obj_set_style_arc_color(cui_TachoBar, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(cui_TachoBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(cui_TachoBar, 32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(cui_TachoBar, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_blend_mode(cui_TachoBar, LV_BLEND_MODE_NORMAL, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(cui_TachoBar, 32, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(cui_TachoBar, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_image_src(cui_TachoBar, &ui_img_imgtagauge_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(cui_TachoBar, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_TachoBar, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_TACHOBAR_NUM);
    children[UI_COMP_TACHOBAR_TACHOBAR] = cui_TachoBar;
    lv_obj_add_event_cb(cui_TachoBar, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_TachoBar, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_TachoBar_create_hook(cui_TachoBar);
    return cui_TachoBar;
}

