// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Tft3.5MeIno

#ifndef _UI_COMP_TACHOBAR_H
#define _UI_COMP_TACHOBAR_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT TachoBar
#define UI_COMP_TACHOBAR_TACHOBAR 0
#define _UI_COMP_TACHOBAR_NUM 1
lv_obj_t * ui_TachoBar_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
