// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Tft3.5MeIno

#include "../ui.h"

lv_obj_t * ui_Clk = NULL;
lv_obj_t * ui_Clk_Hour = NULL;
lv_obj_t * ui_Clk_Min = NULL;
lv_obj_t * ui_Clk_Label1 = NULL;
lv_obj_t * ui_Clk_ClkReturn = NULL;
// event funtions
void ui_event_Clk(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_screen_change(&ui_PlsSet, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_PlsSet_screen_init);
    }
}

void ui_event_Clk_ClkReturn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Dark, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Dark_screen_init);
    }
}

// build funtions

void ui_Clk_screen_init(void)
{
    ui_Clk = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Clk, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Clk, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Clk, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Clk_Hour = lv_roller_create(ui_Clk);
    lv_roller_set_options(ui_Clk_Hour,
                          " 0\n 1\n 2\n 3\n 4\n 5\n 6\n 7\n 8\n 9\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23",
                          LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(ui_Clk_Hour, 160);
    lv_obj_set_height(ui_Clk_Hour, 200);
    lv_obj_set_x(ui_Clk_Hour, -80);
    lv_obj_set_y(ui_Clk_Hour, 0);
    lv_obj_set_align(ui_Clk_Hour, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Clk_Hour, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Clk_Hour, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Clk_Hour, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Clk_Hour, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Clk_Hour, -10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Clk_Hour, &ui_font_NUM120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Clk_Hour, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Clk_Hour, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Clk_Hour, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_Clk_Hour, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Clk_Hour, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Clk_Hour, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Clk_Hour, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Clk_Min = lv_roller_create(ui_Clk);
    lv_roller_set_options(ui_Clk_Min,
                          "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59",
                          LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(ui_Clk_Min, 160);
    lv_obj_set_height(ui_Clk_Min, 200);
    lv_obj_set_x(ui_Clk_Min, 80);
    lv_obj_set_y(ui_Clk_Min, 0);
    lv_obj_set_align(ui_Clk_Min, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Clk_Min, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Clk_Min, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Clk_Min, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Clk_Min, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Clk_Min, -10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Clk_Min, &ui_font_NUM120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Clk_Min, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Clk_Min, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Clk_Min, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Clk_Min, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_Clk_Min, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Clk_Min, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Clk_Min, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Clk_Min, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Clk_Label1 = lv_label_create(ui_Clk);
    lv_obj_set_width(ui_Clk_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Clk_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Clk_Label1, 0);
    lv_obj_set_y(ui_Clk_Label1, -8);
    lv_obj_set_align(ui_Clk_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Clk_Label1, ":");
    lv_obj_set_style_text_color(ui_Clk_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Clk_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Clk_Label1, &ui_font_NUM120, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Clk_ClkReturn = lv_label_create(ui_Clk);
    lv_obj_set_width(ui_Clk_ClkReturn, 140);
    lv_obj_set_height(ui_Clk_ClkReturn, 40);
    lv_obj_set_x(ui_Clk_ClkReturn, 165);
    lv_obj_set_y(ui_Clk_ClkReturn, -134);
    lv_obj_set_align(ui_Clk_ClkReturn, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Clk_ClkReturn, "RETURN");
    lv_obj_add_flag(ui_Clk_ClkReturn, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Clk_ClkReturn,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Clk_ClkReturn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Clk_ClkReturn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Clk_ClkReturn, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Clk_ClkReturn, &ui_font_Font30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Clk_ClkReturn, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Clk_ClkReturn, lv_color_hex(0x202020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Clk_ClkReturn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Clk_ClkReturn, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Clk_ClkReturn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Clk_ClkReturn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Clk_ClkReturn, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Clk_ClkReturn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Clk_ClkReturn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_opa(ui_Clk_ClkReturn, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_add_event_cb(ui_Clk_ClkReturn, ui_event_Clk_ClkReturn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Clk, ui_event_Clk, LV_EVENT_ALL, NULL);

}

void ui_Clk_screen_destroy(void)
{
    if(ui_Clk) lv_obj_del(ui_Clk);

    // NULL screen variables
    ui_Clk = NULL;
    ui_Clk_Hour = NULL;
    ui_Clk_Min = NULL;
    ui_Clk_Label1 = NULL;
    ui_Clk_ClkReturn = NULL;

}
