// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Tft3.5MeIno

#ifndef UI_CLK_H
#define UI_CLK_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Clk
extern void ui_Clk_screen_init(void);
extern void ui_Clk_screen_destroy(void);
extern void ui_event_Clk(lv_event_t * e);
extern lv_obj_t * ui_Clk;
extern lv_obj_t * ui_Clk_Hour;
extern lv_obj_t * ui_Clk_Min;
extern lv_obj_t * ui_Clk_Label1;
extern void ui_event_Clk_ClkReturn(lv_event_t * e);
extern lv_obj_t * ui_Clk_ClkReturn;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

