// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Tft3.5MeIno

#ifndef UI_DARK_H
#define UI_DARK_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Dark
extern void ui_Dark_screen_init(void);
extern void ui_Dark_screen_destroy(void);
extern lv_obj_t * ui_Dark;
extern lv_obj_t * ui_Dark_SpLineDark;
extern void ui_event_Dark_ClockDark(lv_event_t * e);
extern lv_obj_t * ui_Dark_ClockDark;
extern lv_obj_t * ui_Dark_SpDgDark;
extern lv_obj_t * ui_Dark_SpDgDark100;
extern void ui_event_Dark_OdoTripDark(lv_event_t * e);
extern lv_obj_t * ui_Dark_OdoTripDark;
extern lv_obj_t * ui_Dark_OdoLblDark;
extern lv_obj_t * ui_Dark_TripLblDark;
extern void ui_event_Dark_LfwDark(lv_event_t * e);
extern lv_obj_t * ui_Dark_LfwDark;
extern void ui_event_Dark_SwDark(lv_event_t * e);
extern lv_obj_t * ui_Dark_SwDark;
extern lv_obj_t * ui_Dark_NeutDark;
extern lv_obj_t * ui_Dark_TaDgDark;
extern lv_obj_t * ui_Dark_TachoBarDark;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

