// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Tft3.5MeIno

#include "../ui.h"

lv_obj_t * ui_Dark = NULL;
lv_obj_t * ui_Dark_SpLineDark = NULL;
lv_obj_t * ui_Dark_ClockDark = NULL;
lv_obj_t * ui_Dark_SpDgDark = NULL;
lv_obj_t * ui_Dark_SpDgDark100 = NULL;
lv_obj_t * ui_Dark_OdoTripDark = NULL;
lv_obj_t * ui_Dark_OdoLblDark = NULL;
lv_obj_t * ui_Dark_TripLblDark = NULL;
lv_obj_t * ui_Dark_LfwDark = NULL;
lv_obj_t * ui_Dark_SwDark = NULL;
lv_obj_t * ui_Dark_NeutDark = NULL;
lv_obj_t * ui_Dark_TaDgDark = NULL;
lv_obj_t * ui_Dark_TachoBarDark = NULL;
// event funtions
void ui_event_Dark_ClockDark(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_screen_change(&ui_Clk, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Clk_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Clk, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Clk_screen_init);
    }
}

void ui_event_Dark_OdoTripDark(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        TripClickD(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        TripLongD(e);
    }
}

void ui_event_Dark_LfwDark(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        LfwLongD(e);
    }
}

void ui_event_Dark_SwDark(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Light, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Light_screen_init);
    }
}

// build funtions

void ui_Dark_screen_init(void)
{
    ui_Dark = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Dark, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Dark, &ui_img_imgbg_dark_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dark_SpLineDark = lv_obj_create(ui_Dark);
    lv_obj_set_width(ui_Dark_SpLineDark, 230);
    lv_obj_set_height(ui_Dark_SpLineDark, 40);
    lv_obj_set_x(ui_Dark_SpLineDark, 44);
    lv_obj_set_y(ui_Dark_SpLineDark, 75);
    lv_obj_set_align(ui_Dark_SpLineDark, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Dark_SpLineDark, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Dark_SpLineDark, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Dark_SpLineDark, 160, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Dark_SpLineDark, lv_color_hex(0xA0A0A0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Dark_SpLineDark, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Dark_SpLineDark, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dark_ClockDark = lv_textarea_create(ui_Dark);
    lv_obj_set_width(ui_Dark_ClockDark, 140);
    lv_obj_set_height(ui_Dark_ClockDark, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_Dark_ClockDark, 168);
    lv_obj_set_y(ui_Dark_ClockDark, -136);
    lv_obj_set_align(ui_Dark_ClockDark, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_Dark_ClockDark, 6);
    lv_textarea_set_text(ui_Dark_ClockDark, "--:--");
    lv_textarea_set_placeholder_text(ui_Dark_ClockDark, "Placeholder...");
    lv_textarea_set_one_line(ui_Dark_ClockDark, true);
    lv_obj_remove_flag(ui_Dark_ClockDark,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Dark_ClockDark, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Dark_ClockDark, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Dark_ClockDark, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Dark_ClockDark, &ui_font_Num60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Dark_ClockDark, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Dark_ClockDark, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Dark_ClockDark, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Dark_ClockDark, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Dark_ClockDark, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Dark_ClockDark, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Dark_ClockDark, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Dark_ClockDark, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_opa(ui_Dark_ClockDark, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Dark_SpDgDark = lv_textarea_create(ui_Dark);
    lv_obj_set_width(ui_Dark_SpDgDark, 220);
    lv_obj_set_height(ui_Dark_SpDgDark, LV_SIZE_CONTENT);    /// 140
    lv_obj_set_x(ui_Dark_SpDgDark, 64);
    lv_obj_set_y(ui_Dark_SpDgDark, 10);
    lv_obj_set_align(ui_Dark_SpDgDark, LV_ALIGN_CENTER);
    lv_textarea_set_accepted_chars(ui_Dark_SpDgDark, " 0123456789");
    lv_textarea_set_max_length(ui_Dark_SpDgDark, 2);
    lv_textarea_set_text(ui_Dark_SpDgDark, "0");
    lv_textarea_set_placeholder_text(ui_Dark_SpDgDark, "Placeholder...");
    lv_textarea_set_one_line(ui_Dark_SpDgDark, true);
    lv_obj_remove_flag(ui_Dark_SpDgDark,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Dark_SpDgDark, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Dark_SpDgDark, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Dark_SpDgDark, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Dark_SpDgDark, &ui_font_Sp200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Dark_SpDgDark, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Dark_SpDgDark, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Dark_SpDgDark, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dark_SpDgDark100 = lv_textarea_create(ui_Dark);
    lv_obj_set_width(ui_Dark_SpDgDark100, 60);
    lv_obj_set_height(ui_Dark_SpDgDark100, LV_SIZE_CONTENT);    /// 140
    lv_obj_set_x(ui_Dark_SpDgDark100, -60);
    lv_obj_set_y(ui_Dark_SpDgDark100, 43);
    lv_obj_set_align(ui_Dark_SpDgDark100, LV_ALIGN_CENTER);
    lv_textarea_set_accepted_chars(ui_Dark_SpDgDark100, " 1");
    lv_textarea_set_max_length(ui_Dark_SpDgDark100, 3);
    lv_textarea_set_text(ui_Dark_SpDgDark100, " ");
    lv_textarea_set_placeholder_text(ui_Dark_SpDgDark100, "Placeholder...");
    lv_textarea_set_one_line(ui_Dark_SpDgDark100, true);
    lv_obj_remove_flag(ui_Dark_SpDgDark100,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Dark_SpDgDark100, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Dark_SpDgDark100, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Dark_SpDgDark100, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Dark_SpDgDark100, &ui_font_Sp100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Dark_SpDgDark100, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Dark_SpDgDark100, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Dark_SpDgDark100, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Dark_SpDgDark100, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dark_OdoTripDark = lv_textarea_create(ui_Dark);
    lv_obj_set_width(ui_Dark_OdoTripDark, 154);
    lv_obj_set_height(ui_Dark_OdoTripDark, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_Dark_OdoTripDark, 114);
    lv_obj_set_y(ui_Dark_OdoTripDark, 136);
    lv_obj_set_align(ui_Dark_OdoTripDark, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_Dark_OdoTripDark, 5);
    lv_textarea_set_text(ui_Dark_OdoTripDark, "00000");
    lv_textarea_set_placeholder_text(ui_Dark_OdoTripDark, "Placeholder...");
    lv_textarea_set_one_line(ui_Dark_OdoTripDark, true);
    lv_obj_remove_flag(ui_Dark_OdoTripDark,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Dark_OdoTripDark, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Dark_OdoTripDark, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Dark_OdoTripDark, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Dark_OdoTripDark, &ui_font_Num60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Dark_OdoTripDark, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Dark_OdoTripDark, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Dark_OdoTripDark, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Dark_OdoTripDark, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Dark_OdoTripDark, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Dark_OdoTripDark, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Dark_OdoTripDark, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dark_OdoLblDark = lv_label_create(ui_Dark);
    lv_obj_set_width(ui_Dark_OdoLblDark, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Dark_OdoLblDark, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dark_OdoLblDark, 6);
    lv_obj_set_y(ui_Dark_OdoLblDark, 127);
    lv_obj_set_align(ui_Dark_OdoLblDark, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Dark_OdoLblDark, "ODO");
    lv_obj_add_flag(ui_Dark_OdoLblDark, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_Dark_OdoLblDark,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_Dark_OdoLblDark, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Dark_OdoLblDark, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Dark_OdoLblDark, &ui_font_Font30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Dark_OdoLblDark, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Dark_OdoLblDark, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dark_TripLblDark = lv_label_create(ui_Dark);
    lv_obj_set_width(ui_Dark_TripLblDark, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Dark_TripLblDark, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dark_TripLblDark, 4);
    lv_obj_set_y(ui_Dark_TripLblDark, 147);
    lv_obj_set_align(ui_Dark_TripLblDark, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Dark_TripLblDark, "TRIP");
    lv_obj_set_style_text_color(ui_Dark_TripLblDark, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Dark_TripLblDark, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Dark_TripLblDark, &ui_font_Font30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Dark_TripLblDark, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Dark_TripLblDark, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dark_LfwDark = lv_imagebutton_create(ui_Dark);
    lv_imagebutton_set_src(ui_Dark_LfwDark, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_imglfw_png, NULL);
    lv_imagebutton_set_src(ui_Dark_LfwDark, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_imglfw_png, NULL);
    lv_obj_set_width(ui_Dark_LfwDark, 48);
    lv_obj_set_height(ui_Dark_LfwDark, 48);
    lv_obj_set_x(ui_Dark_LfwDark, -208);
    lv_obj_set_y(ui_Dark_LfwDark, 0);
    lv_obj_set_align(ui_Dark_LfwDark, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dark_LfwDark, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_Dark_LfwDark, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_Dark_LfwDark, 4, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_color(ui_Dark_LfwDark, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_opa(ui_Dark_LfwDark, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_width(ui_Dark_LfwDark, 2, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Dark_SwDark = lv_imagebutton_create(ui_Dark);
    lv_imagebutton_set_src(ui_Dark_SwDark, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_imgdaylight_png, NULL);
    lv_imagebutton_set_src(ui_Dark_SwDark, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_imgdaylight_png, NULL);
    lv_obj_set_width(ui_Dark_SwDark, 48);
    lv_obj_set_height(ui_Dark_SwDark, 48);
    lv_obj_set_x(ui_Dark_SwDark, -208);
    lv_obj_set_y(ui_Dark_SwDark, -128);
    lv_obj_set_align(ui_Dark_SwDark, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Dark_SwDark, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_Dark_SwDark, 8, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_color(ui_Dark_SwDark, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_opa(ui_Dark_SwDark, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_width(ui_Dark_SwDark, 2, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Dark_NeutDark = lv_image_create(ui_Dark);
    lv_image_set_src(ui_Dark_NeutDark, &ui_img_imgneut_png);
    lv_obj_set_width(ui_Dark_NeutDark, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Dark_NeutDark, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dark_NeutDark, 0);
    lv_obj_set_y(ui_Dark_NeutDark, 10);
    lv_obj_set_align(ui_Dark_NeutDark, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dark_NeutDark, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_Dark_NeutDark,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Dark_TaDgDark = lv_textarea_create(ui_Dark);
    lv_obj_set_width(ui_Dark_TaDgDark, 120);
    lv_obj_set_height(ui_Dark_TaDgDark, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_Dark_TaDgDark, -173);
    lv_obj_set_y(ui_Dark_TaDgDark, 136);
    lv_obj_set_align(ui_Dark_TaDgDark, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_Dark_TaDgDark, 6);
    lv_textarea_set_text(ui_Dark_TaDgDark, "0000");
    lv_textarea_set_placeholder_text(ui_Dark_TaDgDark, "Placeholder...");
    lv_textarea_set_one_line(ui_Dark_TaDgDark, true);
    lv_obj_remove_flag(ui_Dark_TaDgDark,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Dark_TaDgDark, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Dark_TaDgDark, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Dark_TaDgDark, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Dark_TaDgDark, &ui_font_Num60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Dark_TaDgDark, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Dark_TaDgDark, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Dark_TaDgDark, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Dark_TaDgDark, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Dark_TaDgDark, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Dark_TaDgDark, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Dark_TaDgDark, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dark_TachoBarDark = ui_TachoBar_create(ui_Dark);
    lv_obj_set_x(ui_Dark_TachoBarDark, -20);
    lv_obj_set_y(ui_Dark_TachoBarDark, 0);

    lv_obj_add_event_cb(ui_Dark_ClockDark, ui_event_Dark_ClockDark, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Dark_OdoTripDark, ui_event_Dark_OdoTripDark, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Dark_LfwDark, ui_event_Dark_LfwDark, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Dark_SwDark, ui_event_Dark_SwDark, LV_EVENT_ALL, NULL);

}

void ui_Dark_screen_destroy(void)
{
    if(ui_Dark) lv_obj_del(ui_Dark);

    // NULL screen variables
    ui_Dark = NULL;
    ui_Dark_SpLineDark = NULL;
    ui_Dark_ClockDark = NULL;
    ui_Dark_SpDgDark = NULL;
    ui_Dark_SpDgDark100 = NULL;
    ui_Dark_OdoTripDark = NULL;
    ui_Dark_OdoLblDark = NULL;
    ui_Dark_TripLblDark = NULL;
    ui_Dark_LfwDark = NULL;
    ui_Dark_SwDark = NULL;
    ui_Dark_NeutDark = NULL;
    ui_Dark_TaDgDark = NULL;
    ui_Dark_TachoBarDark = NULL;

}
