// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Tft3.5MeIno

#ifndef UI_LIGHT_H
#define UI_LIGHT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Light
extern void ui_Light_screen_init(void);
extern void ui_Light_screen_destroy(void);
extern lv_obj_t * ui_Light;
extern lv_obj_t * ui_Light_SpLineLight;
extern void ui_event_Light_ClockLight(lv_event_t * e);
extern lv_obj_t * ui_Light_ClockLight;
extern lv_obj_t * ui_Light_SpDgLight;
extern lv_obj_t * ui_Light_SpDgLight100;
extern void ui_event_Light_OdoTripLight(lv_event_t * e);
extern lv_obj_t * ui_Light_OdoTripLight;
extern lv_obj_t * ui_Light_OdoLblLight;
extern lv_obj_t * ui_Light_TripLblLight;
extern void ui_event_Light_LfwLight(lv_event_t * e);
extern lv_obj_t * ui_Light_LfwLight;
extern void ui_event_Light_SwLight(lv_event_t * e);
extern lv_obj_t * ui_Light_SwLight;
extern lv_obj_t * ui_Light_NeutLight;
extern lv_obj_t * ui_Light_TaDgLight;
extern lv_obj_t * ui_Light_TachoBarLight;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

