// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Tft3.5MeIno

#include "../ui.h"

lv_obj_t * ui_Light = NULL;
lv_obj_t * ui_Light_SpLineLight = NULL;
lv_obj_t * ui_Light_ClockLight = NULL;
lv_obj_t * ui_Light_SpDgLight = NULL;
lv_obj_t * ui_Light_SpDgLight100 = NULL;
lv_obj_t * ui_Light_OdoTripLight = NULL;
lv_obj_t * ui_Light_OdoLblLight = NULL;
lv_obj_t * ui_Light_TripLblLight = NULL;
lv_obj_t * ui_Light_LfwLight = NULL;
lv_obj_t * ui_Light_SwLight = NULL;
lv_obj_t * ui_Light_NeutLight = NULL;
lv_obj_t * ui_Light_TaDgLight = NULL;
lv_obj_t * ui_Light_TachoBarLight = NULL;
// event funtions
void ui_event_Light_ClockLight(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Clk, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Clk_screen_init);
    }
}

void ui_event_Light_OdoTripLight(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        TripClickL(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        TripLongL(e);
    }
}

void ui_event_Light_LfwLight(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        LfwLongL(e);
    }
}

void ui_event_Light_SwLight(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Dark, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Dark_screen_init);
    }
}

// build funtions

void ui_Light_screen_init(void)
{
    ui_Light = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Light, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE |
                       LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_style_bg_image_src(ui_Light, &ui_img_imgbg_light_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Light_SpLineLight = lv_obj_create(ui_Light);
    lv_obj_set_width(ui_Light_SpLineLight, 230);
    lv_obj_set_height(ui_Light_SpLineLight, 40);
    lv_obj_set_x(ui_Light_SpLineLight, 44);
    lv_obj_set_y(ui_Light_SpLineLight, 75);
    lv_obj_set_align(ui_Light_SpLineLight, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Light_SpLineLight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Light_SpLineLight, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Light_SpLineLight, 160, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Light_SpLineLight, lv_color_hex(0x0080FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Light_SpLineLight, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Light_SpLineLight, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Light_ClockLight = lv_textarea_create(ui_Light);
    lv_obj_set_width(ui_Light_ClockLight, 140);
    lv_obj_set_height(ui_Light_ClockLight, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_Light_ClockLight, 168);
    lv_obj_set_y(ui_Light_ClockLight, -136);
    lv_obj_set_align(ui_Light_ClockLight, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_Light_ClockLight, 6);
    lv_textarea_set_text(ui_Light_ClockLight, "--:--");
    lv_textarea_set_placeholder_text(ui_Light_ClockLight, "Placeholder...");
    lv_textarea_set_one_line(ui_Light_ClockLight, true);
    lv_obj_remove_flag(ui_Light_ClockLight,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Light_ClockLight, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Light_ClockLight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Light_ClockLight, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Light_ClockLight, &ui_font_Num60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Light_ClockLight, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Light_ClockLight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Light_ClockLight, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Light_ClockLight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Light_ClockLight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Light_ClockLight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Light_ClockLight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Light_ClockLight, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_opa(ui_Light_ClockLight, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Light_SpDgLight = lv_textarea_create(ui_Light);
    lv_obj_set_width(ui_Light_SpDgLight, 220);
    lv_obj_set_height(ui_Light_SpDgLight, LV_SIZE_CONTENT);    /// 140
    lv_obj_set_x(ui_Light_SpDgLight, 64);
    lv_obj_set_y(ui_Light_SpDgLight, 10);
    lv_obj_set_align(ui_Light_SpDgLight, LV_ALIGN_CENTER);
    lv_textarea_set_accepted_chars(ui_Light_SpDgLight, "0123456789");
    lv_textarea_set_max_length(ui_Light_SpDgLight, 2);
    lv_textarea_set_text(ui_Light_SpDgLight, "0");
    lv_textarea_set_placeholder_text(ui_Light_SpDgLight, "Placeholder...");
    lv_textarea_set_one_line(ui_Light_SpDgLight, true);
    lv_obj_remove_flag(ui_Light_SpDgLight,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Light_SpDgLight, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Light_SpDgLight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Light_SpDgLight, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Light_SpDgLight, &ui_font_Sp200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Light_SpDgLight, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Light_SpDgLight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Light_SpDgLight, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Light_SpDgLight100 = lv_textarea_create(ui_Light);
    lv_obj_set_width(ui_Light_SpDgLight100, 60);
    lv_obj_set_height(ui_Light_SpDgLight100, LV_SIZE_CONTENT);    /// 140
    lv_obj_set_x(ui_Light_SpDgLight100, -60);
    lv_obj_set_y(ui_Light_SpDgLight100, 43);
    lv_obj_set_align(ui_Light_SpDgLight100, LV_ALIGN_CENTER);
    lv_textarea_set_accepted_chars(ui_Light_SpDgLight100, " 1");
    lv_textarea_set_max_length(ui_Light_SpDgLight100, 1);
    lv_textarea_set_text(ui_Light_SpDgLight100, " ");
    lv_textarea_set_placeholder_text(ui_Light_SpDgLight100, "Placeholder...");
    lv_textarea_set_one_line(ui_Light_SpDgLight100, true);
    lv_obj_remove_flag(ui_Light_SpDgLight100,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Light_SpDgLight100, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Light_SpDgLight100, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Light_SpDgLight100, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Light_SpDgLight100, &ui_font_Sp100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Light_SpDgLight100, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Light_SpDgLight100, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Light_SpDgLight100, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Light_OdoTripLight = lv_textarea_create(ui_Light);
    lv_obj_set_width(ui_Light_OdoTripLight, 154);
    lv_obj_set_height(ui_Light_OdoTripLight, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_Light_OdoTripLight, 114);
    lv_obj_set_y(ui_Light_OdoTripLight, 136);
    lv_obj_set_align(ui_Light_OdoTripLight, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_Light_OdoTripLight, 6);
    lv_textarea_set_text(ui_Light_OdoTripLight, "00000");
    lv_textarea_set_placeholder_text(ui_Light_OdoTripLight, "Placeholder...");
    lv_textarea_set_one_line(ui_Light_OdoTripLight, true);
    lv_obj_remove_flag(ui_Light_OdoTripLight,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Light_OdoTripLight, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Light_OdoTripLight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Light_OdoTripLight, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Light_OdoTripLight, &ui_font_Num60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Light_OdoTripLight, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Light_OdoTripLight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Light_OdoTripLight, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Light_OdoTripLight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Light_OdoTripLight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Light_OdoTripLight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Light_OdoTripLight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Light_OdoLblLight = lv_label_create(ui_Light);
    lv_obj_set_width(ui_Light_OdoLblLight, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Light_OdoLblLight, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Light_OdoLblLight, 6);
    lv_obj_set_y(ui_Light_OdoLblLight, 127);
    lv_obj_set_align(ui_Light_OdoLblLight, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Light_OdoLblLight, "ODO");
    lv_obj_add_flag(ui_Light_OdoLblLight, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_Light_OdoLblLight,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_Light_OdoLblLight, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Light_OdoLblLight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Light_OdoLblLight, &ui_font_Font30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Light_OdoLblLight, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Light_OdoLblLight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Light_TripLblLight = lv_label_create(ui_Light);
    lv_obj_set_width(ui_Light_TripLblLight, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Light_TripLblLight, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Light_TripLblLight, 4);
    lv_obj_set_y(ui_Light_TripLblLight, 147);
    lv_obj_set_align(ui_Light_TripLblLight, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Light_TripLblLight, "TRIP");
    lv_obj_set_style_text_color(ui_Light_TripLblLight, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Light_TripLblLight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Light_TripLblLight, &ui_font_Font30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Light_TripLblLight, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Light_TripLblLight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Light_LfwLight = lv_imagebutton_create(ui_Light);
    lv_imagebutton_set_src(ui_Light_LfwLight, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_imglfw_png, NULL);
    lv_imagebutton_set_src(ui_Light_LfwLight, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_imglfw_png, NULL);
    lv_obj_set_width(ui_Light_LfwLight, 48);
    lv_obj_set_height(ui_Light_LfwLight, 48);
    lv_obj_set_x(ui_Light_LfwLight, -208);
    lv_obj_set_y(ui_Light_LfwLight, 0);
    lv_obj_set_align(ui_Light_LfwLight, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Light_LfwLight, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_Light_LfwLight,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_Light_LfwLight, 4, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_color(ui_Light_LfwLight, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_opa(ui_Light_LfwLight, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_width(ui_Light_LfwLight, 2, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Light_SwLight = lv_imagebutton_create(ui_Light);
    lv_imagebutton_set_src(ui_Light_SwLight, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_imgdaylight_png, NULL);
    lv_imagebutton_set_src(ui_Light_SwLight, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_imgdaylight_png, NULL);
    lv_obj_set_width(ui_Light_SwLight, 48);
    lv_obj_set_height(ui_Light_SwLight, 48);
    lv_obj_set_x(ui_Light_SwLight, -208);
    lv_obj_set_y(ui_Light_SwLight, -128);
    lv_obj_set_align(ui_Light_SwLight, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Light_SwLight,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_Light_SwLight, 8, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_color(ui_Light_SwLight, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_opa(ui_Light_SwLight, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_width(ui_Light_SwLight, 2, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Light_NeutLight = lv_image_create(ui_Light);
    lv_image_set_src(ui_Light_NeutLight, &ui_img_imgneut_png);
    lv_obj_set_width(ui_Light_NeutLight, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Light_NeutLight, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Light_NeutLight, 0);
    lv_obj_set_y(ui_Light_NeutLight, 10);
    lv_obj_set_align(ui_Light_NeutLight, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Light_NeutLight, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_Light_NeutLight,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Light_TaDgLight = lv_textarea_create(ui_Light);
    lv_obj_set_width(ui_Light_TaDgLight, 120);
    lv_obj_set_height(ui_Light_TaDgLight, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_Light_TaDgLight, -173);
    lv_obj_set_y(ui_Light_TaDgLight, 136);
    lv_obj_set_align(ui_Light_TaDgLight, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_Light_TaDgLight, 6);
    lv_textarea_set_text(ui_Light_TaDgLight, "0000");
    lv_textarea_set_placeholder_text(ui_Light_TaDgLight, "Placeholder...");
    lv_textarea_set_one_line(ui_Light_TaDgLight, true);
    lv_obj_remove_flag(ui_Light_TaDgLight,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Light_TaDgLight, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Light_TaDgLight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Light_TaDgLight, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Light_TaDgLight, &ui_font_Num60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Light_TaDgLight, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Light_TaDgLight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Light_TaDgLight, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Light_TaDgLight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Light_TaDgLight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Light_TaDgLight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Light_TaDgLight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Light_TachoBarLight = ui_TachoBar_create(ui_Light);
    lv_obj_set_x(ui_Light_TachoBarLight, -20);
    lv_obj_set_y(ui_Light_TachoBarLight, 0);

    lv_obj_add_event_cb(ui_Light_ClockLight, ui_event_Light_ClockLight, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Light_OdoTripLight, ui_event_Light_OdoTripLight, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Light_LfwLight, ui_event_Light_LfwLight, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Light_SwLight, ui_event_Light_SwLight, LV_EVENT_ALL, NULL);

}

void ui_Light_screen_destroy(void)
{
    if(ui_Light) lv_obj_del(ui_Light);

    // NULL screen variables
    ui_Light = NULL;
    ui_Light_SpLineLight = NULL;
    ui_Light_ClockLight = NULL;
    ui_Light_SpDgLight = NULL;
    ui_Light_SpDgLight100 = NULL;
    ui_Light_OdoTripLight = NULL;
    ui_Light_OdoLblLight = NULL;
    ui_Light_TripLblLight = NULL;
    ui_Light_LfwLight = NULL;
    ui_Light_SwLight = NULL;
    ui_Light_NeutLight = NULL;
    ui_Light_TaDgLight = NULL;
    ui_Light_TachoBarLight = NULL;

}
