// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Tft3.5MeIno

#include "../ui.h"

lv_obj_t * ui_Opn = NULL;
// event funtions
void ui_event_Opn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        OpnTouch(e);
    }
}

// build funtions

void ui_Opn_screen_init(void)
{
    ui_Opn = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Opn, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_style_bg_color(ui_Opn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Opn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Opn, &ui_img_imgopape_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Opn, &ui_img_imgophnd_png, LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_image_src(ui_Opn, &ui_img_imgopkws_png, LV_PART_MAIN | LV_STATE_USER_2);
    lv_obj_set_style_bg_image_src(ui_Opn, &ui_img_imgopszk_png, LV_PART_MAIN | LV_STATE_USER_3);
    lv_obj_set_style_bg_image_src(ui_Opn, &ui_img_imgopymh_png, LV_PART_MAIN | LV_STATE_USER_4);

    lv_obj_add_event_cb(ui_Opn, ui_event_Opn, LV_EVENT_ALL, NULL);

}

void ui_Opn_screen_destroy(void)
{
    if(ui_Opn) lv_obj_del(ui_Opn);

    // NULL screen variables
    ui_Opn = NULL;

}
