// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Tft3.5MeIno

#ifndef UI_OPN_H
#define UI_OPN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Opn
extern void ui_Opn_screen_init(void);
extern void ui_Opn_screen_destroy(void);
extern void ui_event_Opn(lv_event_t * e);
extern lv_obj_t * ui_Opn;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

