// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Tft3.5MeIno

#ifndef UI_PLSSET_H
#define UI_PLSSET_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_PlsSet
extern void ui_PlsSet_screen_init(void);
extern void ui_PlsSet_screen_destroy(void);
extern lv_obj_t * ui_PlsSet;
extern lv_obj_t * ui_PlsSet_PlsSetTitle;
extern lv_obj_t * ui_PlsSet_PlsSetTitle1;
extern lv_obj_t * ui_PlsSet_PlsSetTitle2;
extern lv_obj_t * ui_PlsSet_PlsSetTitle3;
extern lv_obj_t * ui_PlsSet_PlsSetTitle4;
extern void ui_event_PlsSet_PlsSetReset(lv_event_t * e);
extern lv_obj_t * ui_PlsSet_PlsSetReset;
extern void ui_event_PlsSet_PlsSetCalibSp(lv_event_t * e);
extern lv_obj_t * ui_PlsSet_PlsSetCalibSp;
extern void ui_event_PlsSet_PlsSetCalibOdo(lv_event_t * e);
extern lv_obj_t * ui_PlsSet_PlsSetCalibOdo;
extern lv_obj_t * ui_PlsSet_PlsSetCalibPls;
extern lv_obj_t * ui_PlsSet_PlsSetPlsRoll;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

