// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: Tft3.5MeIno

#include "../ui.h"

lv_obj_t * ui_PlsSet = NULL;
lv_obj_t * ui_PlsSet_PlsSetTitle = NULL;
lv_obj_t * ui_PlsSet_PlsSetTitle1 = NULL;
lv_obj_t * ui_PlsSet_PlsSetTitle2 = NULL;
lv_obj_t * ui_PlsSet_PlsSetTitle3 = NULL;
lv_obj_t * ui_PlsSet_PlsSetTitle4 = NULL;
lv_obj_t * ui_PlsSet_PlsSetReset = NULL;
lv_obj_t * ui_PlsSet_PlsSetCalibSp = NULL;
lv_obj_t * ui_PlsSet_PlsSetCalibOdo = NULL;
lv_obj_t * ui_PlsSet_PlsSetCalibPls = NULL;
lv_obj_t * ui_PlsSet_PlsSetPlsRoll = NULL;
// event funtions
void ui_event_PlsSet_PlsSetReset(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        PlsSetRst(e);
    }
}

void ui_event_PlsSet_PlsSetCalibSp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        PlsSetCalibSp(e);
    }
}

void ui_event_PlsSet_PlsSetCalibOdo(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        PlsSetCalibOdo(e);
    }
}

// build funtions

void ui_PlsSet_screen_init(void)
{
    ui_PlsSet = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_PlsSet, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE |
                       LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_style_bg_color(ui_PlsSet, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PlsSet, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_PlsSet, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PlsSet, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PlsSet, &ui_font_Num60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PlsSet_PlsSetTitle = lv_label_create(ui_PlsSet);
    lv_obj_set_width(ui_PlsSet_PlsSetTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PlsSet_PlsSetTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PlsSet_PlsSetTitle, 0);
    lv_obj_set_y(ui_PlsSet_PlsSetTitle, -124);
    lv_obj_set_align(ui_PlsSet_PlsSetTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PlsSet_PlsSetTitle, "                SP/ODO PULSE SETTING                ");
    lv_obj_remove_flag(ui_PlsSet_PlsSetTitle,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_PlsSet_PlsSetTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PlsSet_PlsSetTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PlsSet_PlsSetTitle, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_PlsSet_PlsSetTitle, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PlsSet_PlsSetTitle, &ui_font_Font30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PlsSet_PlsSetTitle, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PlsSet_PlsSetTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PlsSet_PlsSetTitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PlsSet_PlsSetTitle, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PlsSet_PlsSetTitle, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PlsSet_PlsSetTitle, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PlsSet_PlsSetTitle1 = lv_label_create(ui_PlsSet);
    lv_obj_set_width(ui_PlsSet_PlsSetTitle1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PlsSet_PlsSetTitle1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PlsSet_PlsSetTitle1, 50);
    lv_obj_set_y(ui_PlsSet_PlsSetTitle1, -70);
    lv_obj_set_align(ui_PlsSet_PlsSetTitle1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_PlsSet_PlsSetTitle1, "1.");
    lv_obj_remove_flag(ui_PlsSet_PlsSetTitle1,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_PlsSet_PlsSetTitle1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PlsSet_PlsSetTitle1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PlsSet_PlsSetTitle1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PlsSet_PlsSetTitle1, &ui_font_Font30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PlsSet_PlsSetTitle2 = lv_label_create(ui_PlsSet);
    lv_obj_set_width(ui_PlsSet_PlsSetTitle2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PlsSet_PlsSetTitle2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PlsSet_PlsSetTitle2, 50);
    lv_obj_set_y(ui_PlsSet_PlsSetTitle2, -10);
    lv_obj_set_align(ui_PlsSet_PlsSetTitle2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_PlsSet_PlsSetTitle2, "2. RUN 1.0KM...");
    lv_obj_remove_flag(ui_PlsSet_PlsSetTitle2,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_PlsSet_PlsSetTitle2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PlsSet_PlsSetTitle2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PlsSet_PlsSetTitle2, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PlsSet_PlsSetTitle2, &ui_font_Font30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PlsSet_PlsSetTitle3 = lv_label_create(ui_PlsSet);
    lv_obj_set_width(ui_PlsSet_PlsSetTitle3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PlsSet_PlsSetTitle3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PlsSet_PlsSetTitle3, 50);
    lv_obj_set_y(ui_PlsSet_PlsSetTitle3, 50);
    lv_obj_set_align(ui_PlsSet_PlsSetTitle3, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_PlsSet_PlsSetTitle3, "3.");
    lv_obj_remove_flag(ui_PlsSet_PlsSetTitle3,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_PlsSet_PlsSetTitle3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PlsSet_PlsSetTitle3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PlsSet_PlsSetTitle3, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PlsSet_PlsSetTitle3, &ui_font_Font30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PlsSet_PlsSetTitle4 = lv_label_create(ui_PlsSet);
    lv_obj_set_width(ui_PlsSet_PlsSetTitle4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PlsSet_PlsSetTitle4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PlsSet_PlsSetTitle4, 50);
    lv_obj_set_y(ui_PlsSet_PlsSetTitle4, 110);
    lv_obj_set_align(ui_PlsSet_PlsSetTitle4, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_PlsSet_PlsSetTitle4, "4. RESTART ENGINE");
    lv_obj_remove_flag(ui_PlsSet_PlsSetTitle4,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_PlsSet_PlsSetTitle4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PlsSet_PlsSetTitle4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PlsSet_PlsSetTitle4, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PlsSet_PlsSetTitle4, &ui_font_Font30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PlsSet_PlsSetReset = lv_label_create(ui_PlsSet);
    lv_obj_set_width(ui_PlsSet_PlsSetReset, LV_SIZE_CONTENT);   /// 80
    lv_obj_set_height(ui_PlsSet_PlsSetReset, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PlsSet_PlsSetReset, -115);
    lv_obj_set_y(ui_PlsSet_PlsSetReset, -69);
    lv_obj_set_align(ui_PlsSet_PlsSetReset, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PlsSet_PlsSetReset, "RESET");
    lv_obj_add_flag(ui_PlsSet_PlsSetReset, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_PlsSet_PlsSetReset,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_PlsSet_PlsSetReset, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PlsSet_PlsSetReset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PlsSet_PlsSetReset, &ui_font_Font30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_PlsSet_PlsSetReset, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_PlsSet_PlsSetReset, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_PlsSet_PlsSetReset, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_PlsSet_PlsSetReset, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_PlsSet_PlsSetReset, 4, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_pad(ui_PlsSet_PlsSetReset, 8, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_PlsSet_PlsSetCalibSp = lv_label_create(ui_PlsSet);
    lv_obj_set_width(ui_PlsSet_PlsSetCalibSp, LV_SIZE_CONTENT);   /// 80
    lv_obj_set_height(ui_PlsSet_PlsSetCalibSp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PlsSet_PlsSetCalibSp, -97);
    lv_obj_set_y(ui_PlsSet_PlsSetCalibSp, 50);
    lv_obj_set_align(ui_PlsSet_PlsSetCalibSp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PlsSet_PlsSetCalibSp, "CALIB.SP");
    lv_obj_add_flag(ui_PlsSet_PlsSetCalibSp, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_PlsSet_PlsSetCalibSp,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_PlsSet_PlsSetCalibSp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PlsSet_PlsSetCalibSp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PlsSet_PlsSetCalibSp, &ui_font_Font30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_PlsSet_PlsSetCalibSp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_PlsSet_PlsSetCalibSp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_PlsSet_PlsSetCalibSp, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_PlsSet_PlsSetCalibSp, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_PlsSet_PlsSetCalibSp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_opa(ui_PlsSet_PlsSetCalibSp, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_width(ui_PlsSet_PlsSetCalibSp, 4, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_pad(ui_PlsSet_PlsSetCalibSp, 8, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_PlsSet_PlsSetCalibOdo = lv_label_create(ui_PlsSet);
    lv_obj_set_width(ui_PlsSet_PlsSetCalibOdo, LV_SIZE_CONTENT);   /// 80
    lv_obj_set_height(ui_PlsSet_PlsSetCalibOdo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PlsSet_PlsSetCalibOdo, 50);
    lv_obj_set_y(ui_PlsSet_PlsSetCalibOdo, 50);
    lv_obj_set_align(ui_PlsSet_PlsSetCalibOdo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PlsSet_PlsSetCalibOdo, "CALIB.ODO");
    lv_obj_add_flag(ui_PlsSet_PlsSetCalibOdo, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_PlsSet_PlsSetCalibOdo,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_PlsSet_PlsSetCalibOdo, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PlsSet_PlsSetCalibOdo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PlsSet_PlsSetCalibOdo, &ui_font_Font30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_PlsSet_PlsSetCalibOdo, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_PlsSet_PlsSetCalibOdo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_PlsSet_PlsSetCalibOdo, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_PlsSet_PlsSetCalibOdo, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_PlsSet_PlsSetCalibOdo, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_opa(ui_PlsSet_PlsSetCalibOdo, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_width(ui_PlsSet_PlsSetCalibOdo, 4, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_pad(ui_PlsSet_PlsSetCalibOdo, 8, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_PlsSet_PlsSetCalibPls = lv_textarea_create(ui_PlsSet);
    lv_obj_set_width(ui_PlsSet_PlsSetCalibPls, 200);
    lv_obj_set_height(ui_PlsSet_PlsSetCalibPls, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_PlsSet_PlsSetCalibPls, 88);
    lv_obj_set_y(ui_PlsSet_PlsSetCalibPls, -21);
    lv_obj_set_align(ui_PlsSet_PlsSetCalibPls, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_PlsSet_PlsSetCalibPls, 5);
    lv_textarea_set_text(ui_PlsSet_PlsSetCalibPls, "00000");
    lv_textarea_set_placeholder_text(ui_PlsSet_PlsSetCalibPls, "Placeholder...");
    lv_textarea_set_one_line(ui_PlsSet_PlsSetCalibPls, true);
    lv_obj_remove_flag(ui_PlsSet_PlsSetCalibPls,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_PlsSet_PlsSetCalibPls, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PlsSet_PlsSetCalibPls, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_PlsSet_PlsSetCalibPls, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PlsSet_PlsSetCalibPls, lv_color_hex(0x404040), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PlsSet_PlsSetCalibPls, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PlsSet_PlsSetCalibPls, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PlsSet_PlsSetCalibPls, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PlsSet_PlsSetCalibPls, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PlsSet_PlsSetCalibPls, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PlsSet_PlsSetCalibPls, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PlsSet_PlsSetPlsRoll = lv_roller_create(ui_PlsSet);
    lv_roller_set_options(ui_PlsSet_PlsSetPlsRoll, "0\n1\n2\n3\n4\n5\n6\n7\n8\n9", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_height(ui_PlsSet_PlsSetPlsRoll, 64);
    lv_obj_set_width(ui_PlsSet_PlsSetPlsRoll, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_PlsSet_PlsSetPlsRoll, 147);
    lv_obj_set_y(ui_PlsSet_PlsSetPlsRoll, -21);
    lv_obj_set_align(ui_PlsSet_PlsSetPlsRoll, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_PlsSet_PlsSetPlsRoll,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_PlsSet_PlsSetPlsRoll, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PlsSet_PlsSetPlsRoll, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PlsSet_PlsSetPlsRoll, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PlsSet_PlsSetPlsRoll, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PlsSet_PlsSetPlsRoll, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_PlsSet_PlsSetPlsRoll, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PlsSet_PlsSetPlsRoll, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_PlsSet_PlsSetReset, ui_event_PlsSet_PlsSetReset, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PlsSet_PlsSetCalibSp, ui_event_PlsSet_PlsSetCalibSp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PlsSet_PlsSetCalibOdo, ui_event_PlsSet_PlsSetCalibOdo, LV_EVENT_ALL, NULL);

}

void ui_PlsSet_screen_destroy(void)
{
    if(ui_PlsSet) lv_obj_del(ui_PlsSet);

    // NULL screen variables
    ui_PlsSet = NULL;
    ui_PlsSet_PlsSetTitle = NULL;
    ui_PlsSet_PlsSetTitle1 = NULL;
    ui_PlsSet_PlsSetTitle2 = NULL;
    ui_PlsSet_PlsSetTitle3 = NULL;
    ui_PlsSet_PlsSetTitle4 = NULL;
    ui_PlsSet_PlsSetReset = NULL;
    ui_PlsSet_PlsSetCalibSp = NULL;
    ui_PlsSet_PlsSetCalibOdo = NULL;
    ui_PlsSet_PlsSetCalibPls = NULL;
    ui_PlsSet_PlsSetPlsRoll = NULL;

}
